# Offense count: 8
Metrics/AbcSize:
  Max: 29

# Offense count: 2
# Configuration parameters: CountComments, ExcludedMethods.
# ExcludedMethods: refine
Metrics/BlockLength:
  Max: 133

# Offense count: 2
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 154

# Offense count: 11
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/MethodLength:
  Max: 25

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 136
