inherit_from:
  - https://raw.githubusercontent.com/leanpanda-com/rubocop/0.89.1/rubocop-rspec.yml
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - "bin/stubs/*"
    - "vendor/**/*"
  DisplayCopNames:
    Enabled: true

RSpec/ContextWording:
  Exclude:
    - "spec/features/**/*"
RSpec/LeakyConstantDeclaration:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/ReturnFromStub:
  Enabled: false
Style/EmptyCaseCondition:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false