inherit_from:
  - https://gitlab.com/snippets/1744945/raw
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - "bin/stubs/*"
  DisplayCopNames:
    Enabled: true

RSpec/ContextWording:
  Exclude:
    - "spec/features/**/*"
RSpec/NestedGroups:
  Max: 4
RSpec/ReturnFromStub:
  Enabled: false
Style/EmptyCaseCondition:
  Enabled: false
