language: ruby
rvm:
  - 2.1.10
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
branches:
  only:
    - master
before_install:
  - gem update --system
  - gem update bundler
script: "bundle exec rspec --tag ~docker"
