language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - jruby-19mode
branches:
  only:
    - master
before_install:
  - gem update --system
  - gem update bundler
script: "bundle exec rspec --tag ~docker"
