name: Tests

on:
  push:
    branches:
      - main
      - feature/*

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '2.6'
          - '2.7'
          - '3.0'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        rubygems: 3.0.3
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
    - name: Read Coverage
      run: |
        echo "COVERAGE=$(cat coverage/coverage_percent.txt)%" >> $GITHUB_ENV
    - name: Create Coverage Badge
      if: ${{ github.ref == 'refs/heads/main' && matrix.ruby == '3.0' }}
      uses: schneegans/dynamic-badges-action@v1.0.0
      with:
        auth: ${{ secrets.BADGES_GIST_ACCESS }}
        gistID: b54fe758bfb405c04bef72dad293d707
        filename: coverage.json
        label: Coverage
        message: ${{ env.COVERAGE }}
        color: brightgreen

    services:
      imap:
        image: antespi/docker-imap-devel:latest
        ports:
        - "8025:25"
        - "8143:143"
        - "8993:993"
        env:
          MAILNAME: example.org
          MAIL_ADDRESS: address@example.org
          MAIL_PASS: pass
